INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj1', 'tech', 1000000, '6/3/19', '9/13/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj2', 'music', 1500000, '6/3/19', '8/3/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj3', 'finance', 2000000, '6/6/19', '9/6/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj4', 'tech', 800000, '6/3/19', '9/13/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj5', 'books', 1000000, '4/3/19', '6/13/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj6', 'music', 1500000, '6/1/19', '8/1/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj7', 'books', 4000000, '6/3/19', '9/13/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj8', 'healthcare', 700000, '5/3/19', '8/13/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj9', 'tech', 1200000, '6/1/19', '9/1/19');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Proj10', 'fintech', 3000000, '6/3/19', '9/13/19');

INSERT INTO users (name, age) VALUES ('John', 45);
INSERT INTO users (name, age) VALUES ('Bill', 40);
INSERT INTO users (name, age) VALUES ('Frank', 35);
INSERT INTO users (name, age) VALUES ('Jill', 32);
INSERT INTO users (name, age) VALUES ('Alex', 47);
INSERT INTO users (name, age) VALUES ('Clarissa', 25);
INSERT INTO users (name, age) VALUES ('Jim', 54);
INSERT INTO users (name, age) VALUES ('John', 65);
INSERT INTO users (name, age) VALUES ('Katie', 54);
INSERT INTO users (name, age) VALUES ('Larry', 49);
INSERT INTO users (name, age) VALUES ('Jessica', 34);
INSERT INTO users (name, age) VALUES ('Gary', 21);
INSERT INTO users (name, age) VALUES ('Sebastian', 70);
INSERT INTO users (name, age) VALUES ('Patrick', 32);
INSERT INTO users (name, age) VALUES ('Nancy', 45);
INSERT INTO users (name, age) VALUES ('Randy', 52);
INSERT INTO users (name, age) VALUES ('Jay', 36);
INSERT INTO users (name, age) VALUES ('Stacy', 39);
INSERT INTO users (name, age) VALUES ('Dana', 61);
INSERT INTO users (name, age) VALUES ('Eric', 34);

INSERT INTO pledges (amount, project_id, user_id) VALUES (400000, 4, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (800000, 3, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (750000), 6, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40000, 1, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000000, 7, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500000, 4, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (80000, 2, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400000, 9, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300000, 10, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400000, 5, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300000, 1, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200000, 4, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400000, 3, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100000, 7, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400000, 8, 4);
